# Семинар 2. Погружаемся в нейроны

### 0. С чего вообще все пошло?

![нейрон](https://aisimple.ru/uploads/posts/2023-06/neuron.jpg)

Из строения нейрона делаем выводы:
- **Дендритов** (входных каналов) может быть **много**
- **Аксон** (выходной канал) может быть только **один** (но в будущем он может ветвиться)

У дендритов есть шипики, и чем больше шипиков, тем больше вклад (**вес**) конкретного дендрита в проводимость сигнала.  
Например: смотря на кошку, больший вклад в распознавание кошки вносят сигналы, получаемые зрительным нервом, нежели ощущения в пятке.

---

Теперь перенесемся к искусственным нейронам, имеем:
- Дендриты (входы)
- Аксон (выход)
- Тело нейрона 

![](https://wiki.loginom.ru/images/artificial-neuron.svg)

Внутри нейрона происходит суммирование всех сигналов с их весами:
$$
S = \sum_{i=1}^{n}{X_i \cdot w_i}
$$

**НО**  
Не все сигналы проходят дальше, иначе от нейронов не было смысла.  
На примере с кошкой представьте, что если бы у вас были закрыты глаза, а вы бы все равно распознавали образ кошки только потому что получаете сигналы от ощущений своей пятки.  
Поэтому нейрону необходимо еще **активироваться**, иначе говоря пропустить сигнал дальше при каких-то условиях, в простейшем случае - пороговая функция, как на рисунке ниже. 

![](https://aisimple.ru/uploads/posts/2020-04/1586743155_step.png)

Теперь перенесем имеющуюся информациию на язык Python.  
Инициализируем наши сигналы и веса.

In [1]:
x1 = 0.1
x2 = 0.3
x3 = 0.4

w1 = 0.2
w2 = -0.3
w3 = -0.1

Суммируем все это

In [2]:
s = x1 * w1 + x2 * w2 + x3 * w3
print(s)

-0.11


In [3]:
if s > 0:
    output_signal = 1
else:
    output_signal = 0
print(output_signal)

0


Нейрон не активировался, потому что суммарный сигнал оказался слишком слабым, чтобы пробить порог функции.  

Какие проблемы у кода выше? 
- Если много входов, то выражение для `s` станет невероятно большим, все придется писать руками.  
- Если хотим менять функцию активации, лучше обернуть ее в функцию Python.  

Можно ли сделать код еще лучше? Можно!

In [4]:
x = [0.1, 0.3, 0.4, 0.4, 0.2]
w = [0.2, -0.3, -0.1, 0.1, 0.5]


def sum_inside_neuron(x_list, w_list):
    output = 0
    for i in range(len(x_list)):
        output += x_list[i] * w_list[i]
    return output


def activation(input_signal):
    if input_signal > 0:
        return 1
    return 0

Проверяем

In [5]:
neuron_sum = sum_inside_neuron(x, w)
print(neuron_sum)

0.030000000000000013


In [6]:
print(activation(neuron_sum))

1


Теперь можем работать со сколь угодно большими по размерам `X` и `W`.

In [7]:
import random

In [8]:
random.random()  # возращает случайное число от 0 до 1

0.949554170077141

In [9]:
x = [random.random() for _ in range(10000)]
w = [random.random() for _ in range(10000)]

neuron_sum = sum_inside_neuron(x, w)
print(neuron_sum)

print(activation(neuron_sum))

2491.287932050427
1


Хорошо, теперь умеем считать выход нашего нейрона для одного наблюдения за раз.  
А если хотим много наблюдений за раз?  
Что значит __много наблюдений__?  
Например, нейрон решает, пойду ли я гулять на основе 3 факторов:
1. Температура на улице
2. Скорость ветра
3. Есть ли у меня настроение гулять

Первые два признака называются __численными/непрерывными__, то есть могут принять любое число. Примеры: все, что можно посчитать и сравнить между собой, _температура_, _деньги_, _скорости_, _расстояния_, _возраст_ и т.д.   
Третий признак является __качественным/категориальным__, то есть может быть. Примеры: все, что нельзя сравнить между собой, и что является качеством объекта, _цвета_, _день недели_, _образование_, _гражданство_, _номер группы студента_.  

Допустим, вчера в 15:00 было -12 градусов на улице, скорость ветра 5 м/c, и у меня не было настроения (0).  
Тогда

In [10]:
x = [-12, 5, 0]
w = [random.random() for _ in range(3)]  # зададим случайные веса

neuron_sum = sum_inside_neuron(x, w)
print(neuron_sum)
print(activation(neuron_sum))

-7.642490687181608
0


Затем, вчера же в 16:00 было -10 градусов, скорость ветра 1 м/c, и у меня есть настроение (1)

In [11]:
x = [-10, 1, 1]
# веса мы не обновляем, нейрон же остался прежним

neuron_sum = sum_inside_neuron(x, w)
print(neuron_sum)
print(activation(neuron_sum))

-7.286353328033779
0


Аналогично я могу собрать данные за все дни года, но неужели придется перепрогонять для каждого x эту ячейку снова и снова?  
**НЕТ**  
Мы умеем писать функции с необходимым функционалом

In [12]:
x_15_00 = [-12, 5, 0]
x_16_00 = [-10, 1, 1]
x_17_00 = [3, 0, 1]
x_18_00 = [5, 3, 0]

x_total = [x_15_00, x_16_00, x_17_00, x_18_00]
print(x_total)

[[-12, 5, 0], [-10, 1, 1], [3, 0, 1], [5, 3, 0]]


Обновляем функции, чтобы они умели работать с листами листов  
Варианта 2:
1. Переписать изначальную функцию  
2. Использовать первоначальную функцию для каждого листа

1 вариант

In [13]:
def sum_inside_neuron(x_list, w_list):
    output = []
    for x_one_list in x_list:
        total_sum = 0
        for i in range(len(x_one_list)):
            total_sum += x_one_list[i] * w_list[i]
        output.append(total_sum)
    return output


def activation(input_signal):
    output = []
    for one_signal in input_signal:
        if one_signal > 0:
            output.append(1)
        else:
            output.append(0)
    return output

In [14]:
sums = sum_inside_neuron(x_total, w)
print(sums)

[-7.642490687181608, -7.286353328033779, 2.505745872342805, 4.925442660131714]


In [15]:
print(activation(sums))

[0, 0, 1, 1]


2 вариант

In [16]:
def sum_inside_neuron(x_list, w_list):
    """Умеет считать сумму для одного наблюдения"""
    output = 0
    for i in range(len(x_list)):
        output += x_list[i] * w_list[i]
    return output


def activation(input_signal):
    """Умеет считать активацию для одного наблюдения"""
    if input_signal > 0:
        return 1
    return 0


def total_sum_inside_neuron(x_list, w_list):
    """Умеет считать сумму для любого количества наблюдений"""
    output = []
    for x_one_list in x_list:
        one_output = sum_inside_neuron(x_one_list, w_list)
        output.append(one_output)
    return output


def total_activation(input_signal):
    """Умеет считать активации для любого количества наблюдений"""
    output = []
    for one_signal in input_signal:
        one_output = activation(one_signal)
        output.append(one_output)
    return output

In [17]:
sums = total_sum_inside_neuron(x_total, w)
print(sums)

[-7.642490687181608, -7.286353328033779, 2.505745872342805, 4.925442660131714]


In [18]:
print(total_activation(sums))

[0, 0, 1, 1]


А насколько это быстро считается?

In [19]:
x_total = [[random.random() for _ in range(3)] for _ in range(5_000_000)]

In [20]:
%%time
sums = total_sum_inside_neuron(x_total, w)

CPU times: total: 1.92 s
Wall time: 5.33 s


In [21]:
%%time
activations = total_activation(sums)

CPU times: total: 656 ms
Wall time: 971 ms


Можно ли быстрее?  
**МОЖНО**

In [22]:
import numpy as np

In [23]:
x_total_np = np.array(x_total)
w_np = np.array(w)

In [24]:
x_total_np

array([[0.72041102, 0.31286999, 0.8133209 ],
       [0.94717387, 0.45976491, 0.51298719],
       [0.94895187, 0.51860254, 0.07472374],
       ...,
       [0.56306288, 0.90407426, 0.55142471],
       [0.07088362, 0.95047693, 0.52096639],
       [0.14425682, 0.12072369, 0.03268298]])

In [25]:
w_np

array([0.77958501, 0.34250588, 0.16699085])

In [26]:
x_total_np.shape

(5000000, 3)

In [27]:
w_np.shape

(3,)

In [31]:
%%time
output = x_total_np @ w_np

CPU times: total: 31.2 ms
Wall time: 26 ms


In [32]:
output

array([0.80459859, 0.9815389 , 0.92989125, ..., 0.84068901, 0.46780036,
       0.15926679])

In [30]:
output.shape

(5000000,)

In [33]:
m1 = np.random.random((5023, 42))
m2 = np.random.random((42, 4023))

In [ ]:
[[1, 2, 3],     [[2, 3],          [[1 * 2 + 2 * 4 + 3 + 6, ]]
 [2, 3, 4]]      [4, 5],
                 [6, 7]]
    (2, 3)       (3, 2)     ->    (2, 2)

In [35]:
m1.shape

(5023, 42)

In [36]:
m2.shape

(42, 4023)

In [37]:
(m1 @ m2).shape

(5023, 4023)

In [ ]:
(50, 10) @ (12, 40)

In [ ]:
(15, 12) @ (12, 17) -> (15, 17)

In [38]:
%%time
output = x_total_np @ w_np  # через @ обозначается скалярное произведение векторов/матриц

CPU times: total: 15.6 ms
Wall time: 57.2 ms


In [39]:
%%time
activation_vectorized = np.vectorize(activation)
activations_np = activation_vectorized(output)

CPU times: total: 719 ms
Wall time: 1.02 s


In [40]:
activations[:10]

[1, 1, 1, 1, 1, 1, 1, 1, 1, 1]

In [41]:
activations_np[:10]

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [42]:
sums[:5]

[0.8045985913702441,
 0.9815389028232118,
 0.9298912506316823,
 0.27791459447719036,
 0.6769036805205781]

4.32 секунды VS 10.3 миллисекунды

In [45]:
profit = 5.33 * 1e3 / 57.2
print("Быстрее в", round(profit), "раз!")

Быстрее в 93 раз!


# Библиотеки

**NumPy** (https://numpy.org) -- библиотека для работы с массивами.  
Работаем с примерами отсюда https://numpy.org/doc/stable/user/quickstart.html#the-basics

In [58]:
a = np.arange(15)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [59]:
a.shape

(15,)

In [60]:
type(a)

numpy.ndarray

In [62]:
a = a.reshape(3, 5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [63]:
a.shape

(3, 5)

In [64]:
a.dtype

dtype('int32')

In [65]:
type(a)

numpy.ndarray

In [66]:
b = [2, 3, 4]
a = np.array(b)
a

array([2, 3, 4])

In [67]:
a.dtype

dtype('int32')

In [68]:
b = np.array([1.2, 3.5, 5.1])
b.dtype

dtype('float64')

In [69]:
b = np.array([(1.5, 2, 3), (4, 5, 6)])
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [70]:
b.dtype

dtype('float64')

In [71]:
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [74]:
np.ones((2, 3, 4), dtype=np.int16)

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [75]:
np.arange(10, 30, 5)

array([10, 15, 20, 25])

In [76]:
np.arange(0, 2, 0.3)

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8])

Операции с массивами

In [78]:
a = np.array([20, 30, 40, 50])
b = np.arange(4)
print(a)
print(b)

[20 30 40 50]
[0 1 2 3]


In [79]:
c = a - b
c

array([20, 29, 38, 47])

In [83]:
b ** 2

array([0, 1, 4, 9])

In [84]:
b * 10

array([ 0, 10, 20, 30])

In [86]:
10 * np.sin(a)

array([ 9.12945251, -9.88031624,  7.4511316 , -2.62374854])

In [88]:
a

array([20, 30, 40, 50])

In [87]:
a < 35

array([ True,  True, False, False])

In [91]:
a[a < 35]

array([20, 30])

In [92]:
a = np.arange(12).reshape(6, 2)
a

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [93]:
a.T

array([[ 0,  2,  4,  6,  8, 10],
       [ 1,  3,  5,  7,  9, 11]])

In [94]:
a.shape

(6, 2)

In [95]:
a.T.shape

(2, 6)

In [96]:
a @ a.T

array([[  1,   3,   5,   7,   9,  11],
       [  3,  13,  23,  33,  43,  53],
       [  5,  23,  41,  59,  77,  95],
       [  7,  33,  59,  85, 111, 137],
       [  9,  43,  77, 111, 145, 179],
       [ 11,  53,  95, 137, 179, 221]])

In [97]:
(a @ a.T).shape

(6, 6)

In [98]:
a.T @ a

array([[220, 250],
       [250, 286]])

In [99]:
(a.T @ a).shape

(2, 2)

## Хорошо, но в реальных нейронных сетях не один нейрон, как быть в этом случае?
Вот нейронная сеть чуть посложнее, чем 1 нейрон  
![](https://robocraft.ru/files/neuronet/backpropagation/img01.gif)

Анализируем:
- Имеет два входа
- Потом 3 нейрона
- Потом еще 2
- И потом еще 1

Сгенерируем выборку

In [100]:
x_total = np.random.random(size=(10000, 2))  # (num_obs, num_input_neurons/number of features)

In [101]:
x_total[:5]

array([[0.78944932, 0.07566491],
       [0.47264626, 0.60449812],
       [0.75671481, 0.59431158],
       [0.01785576, 0.40014831],
       [0.00356506, 0.00162829]])

In [102]:
x_total.shape

(10000, 2)

Теперь разберемся с весами:    
У нас 3 нейрона, на каждый из них поступает сигнал с 2 входов.  
В прошлом примере у нас был 1 нейрон с 3 входами, и мы делали `w = [random.random() for _ in range(3)]`  
Теперь нейрон имеет 2 входа, значит `w = [random.random() for _ in range(2)]`

In [103]:
w_1 = [random.random() for _ in range(2)]

In [104]:
w_1

[0.9410268938986819, 0.5372777626740122]

Но таких нейронов 3 штуки, значит, нужно 3 таких листа

In [105]:
w_1 = [random.random() for _ in range(2)]
w_2 = [random.random() for _ in range(2)]
w_3 = [random.random() for _ in range(2)]

Объединим их в один лист

In [106]:
w = [w_1, w_2, w_3]

In [107]:
w

[[0.21392782073607475, 0.4023574915072734],
 [0.30577858626481835, 0.6670269918463135],
 [0.2039828785708525, 0.5646521199339549]]

In [108]:
w = np.array(w)
w.shape

(3, 2)

In [109]:
x_total.shape

(10000, 2)

In [ ]:
X @ W.T

In [112]:
output = x_total @ w.T

In [114]:
output.shape

(10000, 3)

То есть матрица весов будет размером (__количество нейронов в слое__, __количество входных нейронов__)

Если у нас будет 7 нейронов в слое с 3 выходами, то

In [115]:
w = np.random.random(size=(7, 3))

In [116]:
w

array([[0.88746227, 0.37587232, 0.56848174],
       [0.79186653, 0.9313787 , 0.39933679],
       [0.49425885, 0.30247435, 0.28329669],
       [0.78811148, 0.57016365, 0.17807967],
       [0.82449254, 0.70629047, 0.47835629],
       [0.37842472, 0.69489716, 0.9845088 ],
       [0.61923067, 0.57134698, 0.22118021]])

In [117]:
w.shape

(7, 3)

#### Вернемся к нашей изначальной нейросети с 3 нейронами в первом слое и 2 входами

In [118]:
w = np.random.random(size=(3, 2))
w

array([[0.47640043, 0.9582993 ],
       [0.22382104, 0.27011854],
       [0.63867328, 0.98275118]])

У нас есть X, у нас есть W, давайте их женить

In [119]:
x_total.shape

(10000, 2)

In [120]:
w.shape

(3, 2)

Если имеем 10000 наблюдений, то после прохода через 3 нейрона у нас должна быть матрица (10000, 3).  
Имеем матрицы (10000, 2) и (3, 2), как сделать (10000, 3)?

In [121]:
output = x_total @ w.T

In [122]:
output[:5]

array([[0.44860363, 0.19713386, 0.57855997],
       [0.80445901, 0.26907432, 0.89593778],
       [0.93002763, 0.32990327, 1.06735394],
       [0.39196834, 0.11208397, 0.40465022],
       [0.00325879, 0.00123777, 0.00387711]])

In [123]:
output.shape

(10000, 3)

#### Дальше имеем 2 нейрона, где каждый получает сигнал от 3 сзадистоящих.  
Значит

In [124]:
w2 = np.random.random(size=(2, 3))

Как посчитать значения на нейронах дальше?  
Опять умножением

In [125]:
output.shape

(10000, 3)

In [126]:
w2.shape

(2, 3)

Из (10000, 3) и (2, 3) должны получить (10000, 2).

In [127]:
output_2 = output @ w2.T

In [128]:
output_2[:10]

array([[0.70714222, 0.41760782],
       [1.16895896, 0.66314745],
       [1.37352706, 0.7857757 ],
       [0.54723904, 0.30380292],
       [0.00490882, 0.00283638],
       [0.8828713 , 0.51728855],
       [1.19094952, 0.69175072],
       [0.98758554, 0.55513515],
       [0.53787153, 0.30061412],
       [1.05563094, 0.59983645]])

In [129]:
output_2.shape

(10000, 2)

#### В самом конце у нас один нейрон, значит

In [130]:
w3 = np.random.random(size=(1, 2))
output_3 = output_2 @ w3.T

In [131]:
output_3[:10]

array([[0.40370621],
       [0.65964282],
       [0.77694646],
       [0.30692163],
       [0.00278469],
       [0.5028672 ],
       [0.67662765],
       [0.55584146],
       [0.30223852],
       [0.59596983]])

In [132]:
output_3.shape

(10000, 1)

In [133]:
output_3

array([[0.40370621],
       [0.65964282],
       [0.77694646],
       ...,
       [0.86518749],
       [0.40607423],
       [0.92297036]])

Бинго, мы получили 1 чиселко для каждого из 10000 наблюдений в выборке.

![](http://memesmix.net/media/created/l7sksl.jpg)

In [134]:
x_total = np.random.random(size=(970, 10))

In [136]:
import pandas as pd

In [137]:
data = pd.read_csv('https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv', sep=',')

In [139]:
data.shape

(891, 12)

In [ ]:
[img1, img2, ..., img100]

In [ ]:
(100, 3, 224, 224)

In [ ]:
(N, M)

## Это здорово, но как сети учатся?  
Это мы узнаем на следующем семинаре